# Generated by Django 3.2.4 on 2021-06-20 09:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('birthday', models.DateField(null=True, verbose_name='Day of birth')),
                ('course', models.CharField(max_length=2, verbose_name='Course')),
                ('inform', models.TextField(verbose_name='Personal information')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Photo')),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='man', max_length=6)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
