# Generated by Django 3.2.4 on 2021-06-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_customers_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='avatar'),
        ),
    ]
