# Generated by Django 3.2.4 on 2021-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='login')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('salt', models.TextField(verbose_name='salt')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('full_name', models.TextField(verbose_name='full name')),
                ('profile_icon', models.TextField(verbose_name='profile icon')),
                ('self_info', models.TextField(verbose_name='self info')),
                ('is_admin', models.BooleanField(verbose_name='is admin')),
            ],
        ),
    ]
