# Generated by Django 3.2.4 on 2021-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0003_auto_20210604_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(verbose_name='полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(verbose_name='админ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.TextField(verbose_name='изображение профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.TextField(verbose_name='солль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_info',
            field=models.TextField(verbose_name='личная информация'),
        ),
    ]
