# Generated by Django 3.2.4 on 2021-06-10 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampusLife', '0005_alter_user_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(verbose_name='логин')),
                ('password', models.TextField(verbose_name='пароль')),
                ('salt', models.TextField(verbose_name='соль')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('full_name', models.TextField(verbose_name='полное имя')),
                ('profile_icon', models.TextField(blank=True, verbose_name='изображение профиля')),
                ('self_info', models.TextField(blank=True, verbose_name='личная информация')),
                ('is_admin', models.BooleanField(default=False, verbose_name='админ?')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('description', models.TextField(verbose_name='краткое описание')),
                ('event_img', models.ImageField(blank=True, upload_to='C:/media/event_images', verbose_name='изображение для события')),
                ('event_datetime', models.DateTimeField(verbose_name='время события')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to=settings.AUTH_USER_MODEL)),
                ('going_to_event', models.ManyToManyField(blank=True, default=None, related_name='going_to_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Иду', 'Иду'), ('Иду', 'Иду')], default='Иду', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusLife.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайки',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
