# Generated by Django 3.2.4 on 2021-06-15 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampusLife', '0007_auto_20210613_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='going_to_event',
            field=models.ManyToManyField(blank=True, default=None, related_name='going_to_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
