# Generated by Django 3.2.4 on 2021-06-16 05:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampusLife', '0008_alter_event_going_to_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='GoingToEvent',
        ),
        migrations.AlterModelOptions(
            name='goingtoevent',
            options={'verbose_name': 'Идущий на событие', 'verbose_name_plural': 'Идущие на события'},
        ),
    ]
