# Generated by Django 3.2.4 on 2021-06-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0010_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
