# Generated by Django 3.2.4 on 2021-06-17 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampusLife', '0011_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_comments',
            field=models.ManyToManyField(related_name='event_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
