# Generated by Django 3.2.4 on 2021-06-21 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampusLife', '0013_auto_20210618_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_comments',
            field=models.ManyToManyField(blank=True, default=None, related_name='event_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
