# Generated by Django 3.2.4 on 2021-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0015_auto_20210621_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
    ]
