# Generated by Django 3.2.4 on 2021-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0016_alter_comments_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goingtoevent',
            name='value',
            field=models.CharField(choices=[('Пойти', 'Пойти'), ('Уже иду', 'Уже иду')], default='Пойду', max_length=10),
        ),
    ]
