# Generated by Django 3.2.4 on 2021-06-24 15:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CampusLife', '0017_alter_goingtoevent_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ПОльзователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_icon',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='self_info',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(default='', max_length=1, verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='мужчина', max_length=7, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='inform',
            field=models.TextField(default='', verbose_name='Информация о себе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
