# Generated by Django 3.2.4 on 2021-06-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0017_alter_goingtoevent_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(blank=True, upload_to='event_images/%Y/%m/%d', verbose_name='изображение для события'),
        ),
    ]
