# Generated by Django 3.2.4 on 2021-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0018_auto_20210625_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='Мужчина', max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='изображение для события'),
        ),
    ]
