# Generated by Django 3.2.4 on 2021-06-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0019_auto_20210625_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='inform',
        ),
    ]
