# Generated by Django 3.2.4 on 2021-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0021_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inform',
            field=models.TextField(blank=True, verbose_name='Информация о себе'),
        ),
    ]
