# Generated by Django 3.2.4 on 2021-06-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusLife', '0019_auto_20210625_1647'),
        ('CampusLife', '0022_customuser_inform'),
    ]

    operations = [
    ]
