# Generated by Django 3.2.3 on 2021-05-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=200, verbose_name='заголовок')),
                ('news_text', models.TextField(verbose_name='текст новости')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
            ],
        ),
    ]
